### ISSUE TITLE
Tool Icon for Select Effects

### ISSUE THREAD

**Issue by Clyde-L** [xLightsSequencer/xLights#2444] opened 2021-01-04 05:02 UTC
I keep forgetting there is a  Select Effects box.  Can an Icon be added to the tool bar to turn on and off the Select Effects panel?  

thank you Scott!

Clyde L

**Comment by AzGilrock** [comment] 2021-01-04 21:11
I've always wondered why we needed that panel at all.  The toolbar has all the effects plus you can drop any effect and change it with the dropdown in the Effect Settings panel.

**Comment by Clyde-L** [comment] 2021-01-04 23:37
> 
> 
> I've always wondered why we needed that panel at all. The toolbar has all the effects plus you can drop any effect and change it with the dropdown in the Effect Settings panel.

Actually it's quite helpful when helping out other people.  Especially since people don't open/render/save downloaded sequences in the originating layout.  Find Effects is utilized for this and makes quick work of bulk editing of file location for pictures, shaders, and videos.  Again, I keep forgetting about it because there is nothing to remind me it's there.

**Comment by AzGilrock** [comment] 2021-01-05 00:08
Sounds like I was confused.  I thought you meant this panel.
![image](https://user-images.githubusercontent.com/2024669/103592128-6c690f80-4eaf-11eb-8d1f-24cf62e11fd7.png)

**Comment by Clyde-L** [comment] 2021-01-05 00:09
Yeah, sorry I could have posted this originally 
![image](https://user-images.githubusercontent.com/12719816/103592212-6a5b7c80-4ec0-11eb-8460-948c1e79fe49.png)

**Comment by AzGilrock** [comment] 2021-01-05 00:10
Yeah that one is newer.  I was imagining using the other panel to "select" effects.  I always thought it was unnecessary considering its almost a duplicate of the effect toolbar.

**Comment by stevegiron** [comment] 2021-01-05 03:08
I agree it's a dupe.

What would be nice, but I'm not creating a report for is the ability to
disable effects on the toolbar. (Without doing a custom build)
I could do without Life/Tree/Piano/etc. I"m sure others would like this
too. We'd be able to make the icons bigger and have them all fit across the
screen if a few were gone.

**Comment by priemd** [comment] 2021-01-09 02:21
There is an option in preferences under the View tab to change the size....... I can go to Extra Large on a 2560x1440 display and all the effects fit fine, choosing Medium they also all fit on 1600x900 resolution

![image](https://user-images.githubusercontent.com/2279532/104080679-74021e80-51f7-11eb-8727-c2bf6df9a111.png)

**Comment by cybercop23** [comment] 2024-02-05 23:05
Is this still a thing?

**Comment by cybercop23** [comment] 2024-02-26 23:56
Implemented. Will be available in the next release or tonight's nightly build.

**Closed by cybercop23** 2024-02-26 23:56 UTC
Labels: Enhancement, GUI, Sequencer

**Comment by Clyde-L** [comment] 2024-02-27 00:24
Thank you
