### ISSUE TITLE
Data fields not updating when clicking on models

### ISSUE THREAD

**Issue by danberg2** [xLightsSequencer/xLights#3941] opened 2023-08-27 16:24 UTC
**Describe the bug**
When you update any data attribute in xlights, you will lose what you keyed in unless you press the TAB key.  Clicking on any model/object in preview pane, xlights causes the data to be discarded.

**To Reproduce**
For example, in the "Size/Location" area, I am trying to change the "X" coordinates for several models.
 
1. Go to the layout tab in a sequence.
2. Click on the model you want to update.
3. Open the "Size/Location" fields.
4. Update the "X" coordinates for that any model with a new value.
5. Click on the next model you want to update.  You will see that the model will not move to the new "X" coordinates.
6. When you click on the first model, the "X" value reverts to the previous value.

**Expected behavior**
The windows standard (which has been in place for decades) is that when you click on an object after typing text in a field, the text you were typing is updated by the app automatically.  You shouldn't have to type TAB on every field you type before clicking on the next model.

**Screenshots**
(see the three screenshots below)

**Versions (please complete the following information):**
Windows 10
xlights v2023.13

**Additional context**
This bug makes that very problematic when updating the data for multiple models with a keyboard and mouse.

**Attachments**
![bug1](https://github.com/smeighan/xLights/assets/82063393/dcff6fcb-18fb-4ff8-9d22-1c0d5bd6b9bb)
![bug2](https://github.com/smeighan/xLights/assets/82063393/f0f07ff0-29e3-4a49-ac0c-934c39ae5ecb)
![bug3](https://github.com/smeighan/xLights/assets/82063393/8979edb1-cfce-4e91-8b94-ebb9c82576f3)

**Comment by computergeek1507** [comment] 2023-08-27 16:25
You can hit enter as well.

**Comment by computergeek1507** [comment] 2023-08-27 16:31
It's a limitation of the underlying framework xLights uses, probably won't be fixed anytime soon. It may seem like an easy "fix" but it requires rewiring all the layout tab code to not use the propertygrid from WX.

**Comment by danberg2** [comment] 2023-08-27 16:42
You can also press F1 or CTRL-M to update the field too.  What needs to be modified in the source code is to code for the "lost focus" event for all fields to update the internal data with the value keyed in.  This should be a simple fix.

**Comment by computergeek1507** [comment] 2023-08-27 16:45
I'll wait for your poll request then

**Comment by AzGilrock** [comment] 2023-08-27 20:36
Hah.  People that have no clue always say it’s simple

**Comment by computergeek1507** [comment] 2023-08-28 14:20
The problem is we are using the wx framework and the Event you are suggesting to use doesn't exist in the framework. While you may be using mfcgui or Winforms where it does exist. And yes maybe we could get the wx people to implement it, but it probably isn't something easy for them as if it was they probably would have already.

**Comment by cybercop23** [comment] 2024-01-28 23:38
@danberg2 can you please close this issue?

**Comment by danberg2** [comment] 2024-01-31 00:16
This issue has been fixed, even though people said it couldn't because of the framework. Whoever fixed it, THANKS!

**Closed** 2024-01-31 00:20 UTC

**Comment by AzGilrock** [comment] 2024-01-31 01:30
Nope I don't think anything has changed.  I just tried what was in the original description and it still works that way.  Funny thing is clicking on another model does latch the value when I have the 3D checkbox active but if its in 2D it does not latch the value.
