### ISSUE TITLE
Servo default position?

### ISSUE THREAD

**Issue by zakkwillow** [xLightsSequencer/xLights#3318] opened 2022-07-05 01:27 UTC
Is there a way to set a default/neutral/blank position for servos when they are not being commanded? 

My setup is xLights over wifi to an espixelstick running a PCA9685.

**Comment by AzGilrock** [comment] 2022-07-05 01:54
Not currently.  For servos you need to put effects across the entire timeline.  Your request has actually been a desire of mine since I first created the servo ability but it’s not an easy thing to do in xlights. It was designed to be zero when there are no timelines effects.  Also what most would want is not really a default but it would be better if the servos would hold at its last command.

**Comment by zakkwillow** [comment] 2022-07-05 02:55
Ok, I just thought maybe I was missing it in the setup somewhere. 

Now that I know what I'm working with I can figure it out from here.

Thank you for the quick reply!

**Comment by keithsw1111** [comment] 2022-07-05 05:43
The only solution I am aware of is in your player there may be an output processor that given a channel will set a channel to a value whenever it has a zero value. The downside of this ... you cant have zero values ... the upside you have a home position. I know xSchedule has such an output processor and would be surprised if FPP didnt.

**Comment by zakkwillow** [comment] 2022-07-05 13:54
I will give the output processing in xSchedule a try. Ideally, I would really like the servos to just relax between sequences so they don't get hot. I'm definitely overworking them at times. 

I haven't gotten into FPP yet because the boards are hard (read expensive) to get and I would need quite a few of them. So right now the espixelstick firmware and some d1mini clones are doing the job. 

This will be my first year programming my Halloween show and my second year with xLights in general. 

I really appreciate all the feedback and tips as I'm still relatively new to all this.

**Comment by dkulp** [comment] 2022-07-05 14:12
@zakkwillow You are likely better off filing a request with ESPixelStick for 0 behavior options for the PCA9685 output over there.   They could likely add the options to turn off the PWM or similar like the FPP output has.

**Comment by cybercop23** [comment] 2024-02-02 14:59
@zakkwillow @ebuechner anything else left here or can this be closed? If so, please close it.

**Closed** 2024-02-02 15:05 UTC

**Comment by zakkwillow** [comment] 2024-02-02 15:06
Apologies for leaving this open so long. Ended up getting it handled on the hardware side.
