### ISSUE TITLE
Sequence not uploading to FPP

### ISSUE THREAD

**Issue by indyburrell** [xLightsSequencer/xLights#4061] opened 2023-10-17 14:01 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

I have had many failed attempts at uploading FSEQ and media files to FPP via the FPP connect tool on xLights.  I have also tried uploading the FSEQ files directly to the FPP and the sequence doesn't play properly.  This has been happening with any sequence I try.  

When using the FPP connect, it will find my FPP, and I have FSEQ type as V2 Sparse/zstd.  Media is clicked, all models, all UDP out selected.  After I select upload, it will prepare the file to go out, then it will be done quickly.  On the FPP interface, I will just get the patch file and there will be no data in the file.  Currently unable to run any sequences through the FPP.  I am able to run shows from xlights with the output to lights on, and it runs correctly.  Id be happy to send to you one of my sequences.  Thanks for your help to get this problem resolved. 

Currently running xlights 2023.17 and FPP v7.2-2-ge35c0df7 and mac 13.5.2

[xLightsProblem FPP.zip](https://github.com/smeighan/xLights/files/12929680/xLightsProblem.FPP.zip)
<img width="1236" alt="Screenshot 2023-10-16 at 8 21 38 PM" src="https://github.com/smeighan/xLights/assets/148237016/8db6dff8-a6d8-4597-b49f-798ed30d574f">

**Comment by derwin12** [comment] 2023-10-17 14:08
https://github.com/smeighan/xLights/issues/4054

Can you do a tools package logs and upload this to here ..

**Comment by indyburrell** [comment] 2023-10-17 14:53
Also, if it helps, I also tried using my F16V4 as a player, and uploading the FSEQ files to a sd card and putting it onto the board, it is saying "unable to open FSEQ file" when I try to play the playlist.
<img width="1583" alt="Screenshot 2023-10-17 at 8 52 26 AM" src="https://github.com/smeighan/xLights/assets/148237016/6232a10f-dd63-41dc-918b-f7fd890d2597">

**Comment by dkulp** [comment] 2023-10-17 15:14
The php log shows a timeout.  Thus, it's likely either a very slow SD card (or card going bad) or slow network which would be why I wouldn't be able to reproduce it.      Can you ssh in to the FPP instance and run "sudo a2dismod reqtimeout", reboot, and try again?  I'm curious to see if that fixes it or not.

**Comment by Skrodlada21** [comment] 2023-10-17 22:05
I am having the same issues,  I can manually upload them and it works fine, but uploading from FPP Connect in Xlights they are not valid.  It shows they upload but they are in there as a patch file and that file never plays.

**Comment by derwin12** [comment] 2023-10-18 02:45
Similar to https://github.com/smeighan/xLights/issues/4022

**Comment by indyburrell** [comment] 2023-10-18 05:29
No matter the way that I tried to get files to the FPP, I couldn't get them to go.  I ended up playing with different versions of xLights and FPP.  Ended up with 2022.21.2 for xlights and 6.2 for FPP.  FPP connect would still not work, but was able to get the files on via the file manager.  I wish you luck as you work through some of these items and I'll keep trying on my end to get things to work as intended.  Thank you for your help and making a great program!

**Comment by dkulp** [comment] 2023-10-18 07:35
I stuck a 2023.17.1 build at https://dankulp.com/xlights/archive/ Can someone that is having the issue try that?  

I really cannot reproduce this.   The closest I could get was by throttling my connection down to 3G speeds (SLOOWWW) it would timeout and leave the patch0 file, but it would take several minutes to do so, not immediate which is what I see in the logs.

**Comment by Skrodlada21** [comment] 2023-10-20 20:14
@dkulp just letting you know, I upgraded to the 2023.17.1 , when I try and do the FPP connect it uploads within seconds and it says it is done but it still puts a patch file that is not able to be played by FPP.  I am on the updated FPP, as well as the most updated XLights, Attached is my logs from that time, and the screenshot of FPP. It shows the old version of Smells like Teem Spirit and it also added a second one that is just a patch file.  Let me know if you need anything else.  I never got any sort of error from Xlights or FPP. 

[XlightsLog.docx](https://github.com/smeighan/xLights/files/13058278/XlightsLog.docx)
<img width="1500" alt="Screenshot 2023-10-20 at 2 12 43 PM" src="https://github.com/smeighan/xLights/assets/34801576/5c838ee7-9c8e-4e10-9b26-8b49f082b4b7">

**Comment by smtpboy** [comment] 2023-11-19 00:04
I'm having the same problem where corrupt, truncated or just broken fseq files seem to get uploaded with no real pattern, often they're only 10-15kb in size, not the hundreds of mb you'd expect.  This has been happening for several releases now both of xLights and FPP.  I'm currently on 2023.19 and 7.3.3 on FPP.  Exact same issue as outlined by several folks above.  Originally thought it was an issue with FPP 7.3 as I didn't have the issue under 7.2, but I really can't tell with all the changes lately on both codebases and the addition of a number of models to my layout this year.  It seems to happen pretty randomly too which makes it infuriating to troubleshoot.  Positive it is NOT a bad or slow SD card, as i've swapped out all cards involved as well.   Happy to provide any debugs/logs that will assist with this.

**Comment by agent462** [comment] 2023-11-20 21:47
This is also happening regularly for me and almost always a few controllers that have lower network signal.  Yes I use WiFi - it's never been an issue in the past.  
OSX - Xlights 2023.20
FPP v7.3.5

Would be nice for a checksum to happen on the .fseq file prior to upload and comparison after to validate successful upload.  Otherwise FPP Connect always happily acts like everything went fine until you either double check every controller or notice an issue while trying to play the show.  As silly as it sounds, I spent way too long thinking my player couldn't connect to certain remotes properly after "uploading" sequences only to find out they were botched with the patch files.

I can attempt to find some logs and attach later today.

**Comment by agent462** [comment] 2023-11-21 03:08
The most relevant thing I see in the FPP Logs when this happens is this at the same time the file is uploaded and ends up with patch otherwise there is nothing else in various FPP logs:

apache2-error:
[Mon Nov 20 20:32:46.500805 2023] [proxy_fcgi:error] [pid 960:tid 2718950432] (70008)Partial results are valid but processing is incomplete: [client 192.168.0.11:51399] AH01075: Error dispatching request to : (reading input brigade)

Different controller:
[Mon Nov 20 20:55:34.496015 2023] [proxy_fcgi:error] [pid 1019:tid 2711569440] (70008)Partial results are valid but processing is incomplete: [client 192.168.0.11:52044] AH01075: Error dispatching request to : (reading input brigade)
[Mon Nov 20 20:58:26.865363 2023] [proxy_fcgi:error] [pid 1022:tid 2701108256] (70008)Partial results are valid but processing is incomplete: [client 192.168.0.11:52114] AH01075: Error dispatching request to : (reading input brigade)
[Mon Nov 20 21:01:40.948689 2023] [proxy_fcgi:error] [pid 1022:tid 2709500960] (70008)Partial results are valid but processing is incomplete: [client 192.168.0.11:52189] AH01075: Error dispatching request to : (reading input brigade)

<img width="1342" alt="Screenshot 2023-11-20 at 9 07 22 PM" src="https://github.com/smeighan/xLights/assets/242283/b6d48e49-1e0e-47fb-8fe5-cd8f01c612d0">

**Comment by cybercop23** [comment] 2024-01-28 18:46
There wee several fixes for this. @indyburrell can you please re-test and close this if no further issues?

**Closed** 2024-02-02 18:09 UTC
Labels: Waiting for user feedback
