### ISSUE TITLE
render on save preference is off

### ISSUE THREAD

**Issue by morrydavis** [xLightsSequencer/xLights#4279] opened 2024-01-19 01:00 UTC
yet when I do as save sequence modified time on both .xsq and.fseq files are updated.
when I do a render ALL no modified times are changed.
when I do a batch render .fseq files modofied time is changed.
trying to write a program to confirm my .xsq and .fseq files are in sync

**Comment by AzGilrock** [comment] 2024-01-19 13:17
When you hit save its going to save both the xsq and fseq files.  The "render on save" option just determines if a new full render is going to be done first.  As you click on effects renderings are happening so the data for an fseq has already changed even though you haven't hit the render all button.

Render All:  just renders and updates the data in memory

Batch Render: Is opening up multiple files so it has to open, render, and save them.  The "render on save" option has no effect on "batch render" because the whole goal of "batch render" is to render and save the files.

**Comment by AzGilrock** [comment] 2024-01-19 13:20
To me it seems pointless.  There really isn't such thing as an XSQ and FSEQ being "in sync".  There are factors that can make them "out of sync" that have nothing to do with the sequence even being open.  If you make changes to your layout while no sequences are open you just changed what the XSQ file will produce and therefore its now "out of sync" with the FSEQ data.

**Comment by derwin12** [comment] 2024-01-19 14:48
I guess the goal here is to determine if the fseq is ready for your show - so comparing to the .xsq might not even be the best place. If rgbeffects changes .. your fseq could be stale regardless of the date on your .xsq. If the .xsq is newer than the .fseq that is almost certainly (some exceptions of course) mean the fseq is stale. Have to think about this one - I like the idea - would be nice to flag stale fseq files either on fpp connect or somewhere in the pipeline.

**Comment by AzGilrock** [comment] 2024-01-19 15:09
Part of the problem is not all models in a layout necessarily have to be part of a show so its hard to know if the changes affect the sequence without comparing the model affected and whether any channel assignments to existing models in the sequence got shuffled around.  This gets me back to really wanting a new mode in xLights where everything in the layout is always active for every sequence so there would be no picking of models when you create a sequence.  To keep from messing up existing stuff I'd need to make it an option. (SuperGil mode....lol)

**Comment by derwin12** [comment] 2024-01-21 14:36
Doesn't xschedule show the channel count of the layout vs the channel count of the fseq? Is that a good (not perfect) indication that the sequence is rendered correctly? Is that flagged anywhere in fpp connect? or anywhere else?

**Comment by dkulp** [comment] 2024-01-21 16:01
> Doesn't xschedule show the channel count of the layout vs the channel count of the fseq? Is that a good (not perfect) indication that the sequence is rendered correctly? Is that flagged anywhere in fpp connect? or anywhere else?

No, it doesn't.  If you move a prop from one port to another, it wouldn't affect the channel count, but certainly would require a re-render of the fseq.    Also, if you use V2/Sparse, then the fseq would not have the full channel range if the master view doesn't contain all the models.

**Comment by cybercop23** [comment] 2024-01-30 14:33
@morrydavis if you go the info you were looking for, please close this issue.

**Closed** 2024-01-30 17:06 UTC
