### ISSUE TITLE
Default view for new sequences doesnt work.  

### ISSUE THREAD

**Issue by stk21** [xLightsSequencer/xLights#2884] opened 2021-10-25 22:00 UTC
Mac Version of xLights
Version 2021.34

Master view is still the default on new sequences even after the preference save.  

![image](https://user-images.githubusercontent.com/32824148/138776870-cb070b76-f912-4b93-bc09-a83cf7315d83.png)

**Comment by sslupsky** [comment] 2022-02-06 23:35
@AzGilrock I just found this thread and I see what @stk21 is referring to.  I too often click done at the same step and was wondering how to reorder the "default" master view to ensure I have the proper render ordering I want.  Even though I would select a different view after starting a new sequence, I did not realize that changing the view doesn't affect render order.  I did determine that the only thing that affects render order is the master view.  The master view is pretty much a random mess and I was having to reorder the master view manually every time.

The suggestion earlier to select the view when creating the sequence fixes the problem.  I think I understand what is going on here.  When you get to the screen that shows the view list box, "All Models" is the default selection.  When I was clicking "done" here, xLights uses the "All Models" view which is the default view that is the "random" order of models and groups as they were created.  I think part of the confusion is that this is the only place the "All Models" view appears.  This is the view @stk21 is referring to.  I suggest perhaps the "All Models" view should be added to the list of views when you "Edit Display Elements" since it is a view that can be selected when you create a new sequence.

The preference setting does not override this behaviour though I think it is intended to be that way.  Moreover, the preference setting does not stick.  If I change the default view preference, quit xLights and reopen, the setting is reset.  I've included two screenshots below that show the setting before I quit xLights and the setting after restarting.
Before:
![Screen Shot 2022-02-06 at 4 31 20 PM](https://user-images.githubusercontent.com/16888734/152706263-b3b1d11d-2055-4d18-8cf6-809dd3542078.png)

After:
![Screen Shot 2022-02-06 at 4 25 46 PM](https://user-images.githubusercontent.com/16888734/152706154-61da150f-3d64-4956-9c28-d396f65ab52b.png)


I am not sure if this behaviour is different on Windows since I only run xLights on a mac.  Problem may have something to do with wxWidgets and I have not taken a dive into the code yet to look closer at this.

**Comment by sslupsky** [comment] 2022-02-06 23:39
Also, I suggest renaming the "master view" to something more meaningful like "render order view" or maybe just "render view".  This is really what the master view is used for.

**Comment by AzGilrock** [comment] 2022-02-06 23:46
All Models is not a View it just means you’ll get all your models

**Comment by sslupsky** [comment] 2022-02-07 14:20
Understood.  Perhaps then it can be an option when creating a new view to populate the view the "All Models"?  I think doing this helps people understand where the data for the view is coming from.  It may also be helpful to update the manual to include an explanation of this.  The following is quoted from the manual, which incorrectly suggests that "All Models" is a view:

> If intending to create an xLights sequence, on the next screen, select the View that you wish to use on the sequencer screen (use the Drop down if the View displayed is not what you require) and then press Quick Start.

**Comment by sslupsky** [comment] 2022-02-07 14:22
Maybe add a tool tip to the list box that explains it?

**Comment by stk21** [comment] 2022-02-07 15:05
@sslupsky, while this is NOT the solution that I think is needed....  I ended up editing the xlights_rgbeffects.xml file to put the models in the order that I wanted.  This can be tedious, but once its done once, unless you add more items, you shouldnt need to change it again.

It would be a "nice to have" feature to be able to re-order it through the GUI, but my manual workaround did work for me.

**Comment by sslupsky** [comment] 2022-02-07 15:47
I found the problem but I am having difficulty compiling the change to test because this recent commit c17443b from @computergeek1507 broke the macOS build.  I am not very familiar with the processes used here, is it usual to commit something to master that intentionally breaks something?

**Comment by AzGilrock** [comment] 2022-02-07 15:58
The main developers always commit to master and some of us only compile on one platform so it can happen that another platform breaks.  We don't really have a rigid process like if you worked at a company doing software.  Heck even at work we break master sometimes even though we have a review process and continuous integration tests that have to pass to make it into master...lol.

I just got a Macbook Pro so soon I'll be setup to compile for Mac and Windows.  I used to be setup to compile on Mac using a Mac Mini a few years ago but I didn't keep up with it.

**Comment by computergeek1507** [comment] 2022-02-07 16:10
> I found the problem but I am having difficulty compiling the change to test because this recent commit [c17443b](https://github.com/smeighan/xLights/commit/c17443ba386d918d171e6b4ac31aa07bd78233e6) from @computergeek1507 broke the macOS build. I am not very familiar with the processes used here, is it usual to commit something to master that intentionally breaks something?

Dan fixed the Mac Build last night, you just need to update the submodule.

**Comment by sslupsky** [comment] 2022-02-07 16:12
Ok, I didn't update the submodule ... i'll try that, thanks.

**Comment by sslupsky** [comment] 2022-02-07 17:32
i check and I have the current submodule from the master branch but I am still getting a build error.  I do not think @dkulp pushed the submodule changes yet?

```
/Users/stevenslupsky/Documents/source/xLights/xLights/BatchRenderDialog.cpp:151:5: No matching function for call to 'GetAllFilesInDir'
/Users/stevenslupsky/Documents/source/xLights/macOS/macOS-src/osxUtils/ExternalHooksMacOS.h:21:6: Candidate function not viable: requires 3 arguments, but 4 were provided
```

Indeed, the current submodule doesn't have the proper function definition:
https://github.com/xLightsSequencer/xLights-macOS/blob/60dceea1169d4515db5b387bcdc4c16d2043dc09/macOS-src/osxUtils/ExternalHooksMacOS.h#L21

**Comment by AzGilrock** [comment] 2022-02-07 17:43
> Ok @AzGilrock . I'll push the change (without testing since whatever Scott did is not immediately obvious to me how to fix). The change is pretty straight forward. Perhaps you can compile on Windows and let me know it is working. I think this problem exists on both macOS and Windows.

I was telling you what the main developers do not what you should do...lol.

**Comment by sslupsky** [comment] 2022-02-07 17:47
> > Ok @AzGilrock . I'll push the change (without testing since whatever Scott did is not immediately obvious to me how to fix). The change is pretty straight forward. Perhaps you can compile on Windows and let me know it is working. I think this problem exists on both macOS and Windows.
> 
> I was telling you what the main developers do not what you should do...lol.

Hahaha, yeah, I get it.

Anyway, have a look at the commit, I didn't actually make a PR yet but created the commit in my fork so you could have a look.  The issue is pretty straight forward.  I'll eventually get the build to work and will submit a PR.

**Comment by derwin12** [comment] 2022-02-07 19:22
Where I used to work (retired now) .. if you broke master you had to bring in donuts. There were plenty of donuts to be found..lol.

**Comment by sslupsky** [comment] 2022-02-07 19:40
> Where I used to work (retired now) .. if you broke master you had to bring in donuts. There were plenty of donuts to be found..lol.

hahahaha.

I pushed a fix ... build is still not working properly but I fixed the build errors on my end and tested the fix.  Now the preference setting is saved and it is used when you create a new sequence.

**Closed** 2024-02-05 16:31 UTC
