### ISSUE TITLE
When trying to assign a multi-string model using cascaded V2 remotes, the visualizer will not contain the model to a single 4-block of output ports.

### ISSUE THREAD

**Issue by rshoover2001** [xLightsSequencer/xLights#4142] opened 2023-11-20 23:22 UTC
**Describe the bug**
When trying to assign a multi-string model using cascaded V2 remotes, the visualizer will not contain the model to a single 4-block of output ports.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Setup a KulpLights Differential Controller in xlights - any will do.
2. Click on the Visualizer.
3. Attempt to assign a model with more than 4 strings to port 13, and choose smart remotes for that port, and set the number of cascaded remotes to 2.
4. The visualizer assigns the model to go beyond port 16, and when selecting cascaded remotes, xLights moves the whole model to remote C (??) and same behavior cascading down beyond port 16. The "Cascade down port" setting has no effect.

**Expected behavior**
I expect it to work the same way it does for ports below 12, and the way it does on many of my other controllers.

**Screenshots**
<img width="637" alt="Screenshot 2023-11-20 at 6 20 20 PM" src="https://github.com/smeighan/xLights/assets/99098946/690dab1d-f02f-4ee8-9a8f-8f05ebb36885">
<img width="667" alt="Screenshot 2023-11-20 at 6 20 35 PM" src="https://github.com/smeighan/xLights/assets/99098946/fa52dc58-26e4-457d-b206-291d2f2d47d3">
<img width="833" alt="Screenshot 2023-11-20 at 6 20 49 PM" src="https://github.com/smeighan/xLights/assets/99098946/4c14fb4d-0a07-4e53-a35f-4e3164a6d140">
<img width="792" alt="Screenshot 2023-11-20 at 6 20 56 PM" src="https://github.com/smeighan/xLights/assets/99098946/a093de9f-90ac-463d-bcc2-7189bbe3d587">

**Versions (please complete the following information):**
 - OS: MacOS 14.1.1
 - xLights version 2023.20

**Comment by rshoover2001** [comment] 2023-11-22 15:29
Tried this on Windows 11 64-bit as well, same version 2023.20 and same results.

**Comment by derwin12** [comment] 2023-11-23 14:23
This might be related to the recently fixed problem putting on a 3rd remote..

**Comment by dartunder** [comment] 2023-11-23 15:57
Try the nightly, try version 19, or wait for version 21.   I can't reproduce it with the current version.
https://github.com/smeighan/xLights/releases/tag/nightly

**Comment by norcalkev** [comment] 2023-12-02 01:06
I think this is similar to an issue I have hit when I connected an F48v4 to an SRx2 (8 port smart remote). The SRx2 was then connected to a Matrix (864 pixels) using 6 of the strings. I watched how 1a and 1b were assigned to the two banks on the x2 in this video:
https://www.youtube.com/watch?v=qafD5eCUikw
I cannot do the same with my matrix. I can only move based on the first string in visualizer rather than individually.
After all that, I've decided to just connect two four port smart remotes and NOT daisy chain for this matrix. I think it is a bug in xlights visualizer and/or matrix settings. I'll find another use for the SRx2!

**Comment by keithsw1111** [comment] 2023-12-04 10:32
I am pretty certain this is fixed in 21

**Comment by derwin12** [comment] 2024-01-08 01:58
Close this?

**Comment by norcalkev** [comment] 2024-01-08 04:27
Sure!

**Closed** 2024-01-08 09:04 UTC
