### ISSUE TITLE
Crash When Changing to Temp Show Folder

### ISSUE THREAD

**Issue by Darzoom** [xLightsSequencer/xLights#4287] opened 2024-01-22 13:10 UTC
Not Sequence Related

**Describe the bug**
When going into XL and from the controllers tab select Temporary Folder XL crashes.

**To Reproduce**
In description of the bug

**Expected behavior**
Temporary folder opens. 

**Screenshots**
None

**Versions (please complete the following information):**
 - OS: macOS Monterey 12.7.2
 - xLights version 24.1

**Additional context**
I7 Processor

**Attachments**
[xLights_dbgrpt-1586-20240122T075858.zip](https://github.com/xLightsSequencer/xLights/files/14010453/xLights_dbgrpt-1586-20240122T075858.zip)

**Comment by AzGilrock** [comment] 2024-01-22 14:30
Pretty sure this is the loading test presets crash Scott already fixed.

**Comment by Darzoom** [comment] 2024-01-22 17:48
Okay.  I guess I’ll wait for the fix to be pushed.

**Comment by cybercop23** [comment] 2024-01-22 20:52
Duplicate of.. https://github.com/xLightsSequencer/xLights/issues/4277

Try downloading and testing the nightly version and please close

**Comment by Darzoom** [comment] 2024-01-22 22:28
I don’t do nightly builds.  If covered on another ticket I will close.

**Closed** 2024-01-22 22:31 UTC
