### ISSUE TITLE
2023.16 Does not Automatically Close open xlights - Log Attached

### ISSUE THREAD

**Issue by jimswinder** [xLightsSequencer/xLights#4042] opened 2023-10-10 23:28 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Trying to download 2023.16 it does not close open application of xlights...creates bug report
**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2019.15

**Additional context**

**Attachments**

https://www.dropbox.com/scl/fi/2bbhkrn8hozq0tqs0wzup/xLights_dbgrpt-2356-20231010T162041.zip?rlkey=3fe72ekcurojo2twwm5s6l1fi&dl=0

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment] 2023-10-11 07:36
Unfortunately Jim that crash report does not make a lot of sense which makes it hard to do much.

Can I clarify that you started xlights. Did nothing. Got prompted to download. Clicked download. Then maybe closed xlights ... and it crashed on exit?

**Comment by keithsw1111** [comment] 2023-10-11 07:38
Your description says it does not automatically close xlights ... it is not meant to. It just triggers the download ... it is up to you to run it. That is by design. While we could handle all of that in xlights i am not sure it is all that valuable as a feature.

**Comment by derwin12** [comment] 2023-10-11 13:54
(Cant duplicate)
I think he means he is running .15, does the download and starts the install. You get this message 
![image](https://github.com/smeighan/xLights/assets/4643499/7725029a-6633-47c5-b3c1-b6b9e368a2df)

When I click next, it did close .15 and installed and continued just fine.

**Comment by jefft0825** [comment] 2023-10-11 14:04
I actually just did this and it closed out xlights fine.  Went from .15 to .16

**Comment by jimswinder** [comment] 2023-10-11 15:27
Yes..got that window...computer froze up and it created a crash log
________________________________

**Comment by jimswinder** [comment] 2023-10-13 03:24
P {margin-top:0;margin-bottom:0;}

**Comment by dartunder** [comment] 2023-10-25 21:18
Should this be closed as won't fix?

**Comment by cybercop23** [comment] 2024-01-28 18:51
@jimswinder please close.

**Closed** 2024-01-28 18:52 UTC
