### ISSUE TITLE
cannot install xlights on ARM architecture

### ISSUE THREAD

**Issue by ericleco** [xLightsSequencer/xLights#4691] opened 2024-08-02 15:23 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When trying to install xlights on a Snapdragon based laptop, the following error appears: This program can only be installed on versions of windows designed for the following processor architectures: x64

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Download latest xlights version: Windows 64bit | Download 64bit 2024.13  
2. Error message listed in title appears

**Expected behavior**
Ideally, an ARM version of xlights would be compiled however, xlights should be able to run under the x64 emulator.

**Screenshots**
![image](https://github.com/user-attachments/assets/dc57aad7-cb15-4103-9e4a-f4c4aa338189)

**Versions (please complete the following information):**
 - OS: Windows 11 Home 24H2
 - xLights version 2024.13
 
**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.
Windows 64bit 	 [ Download 64bit 2024.13](https://xlights.org/download/3930/)

**Comment by computergeek1507** [comment] 2024-08-02 15:59
Did you attempt to change the "Windows 11 on ARM" properties and disable hybrid emulator option

**Comment by ericleco** [comment] 2024-08-02 16:33
Hi,I just did and have the same issue. Same issue unfortunately. Unless I’m missing something else. Thanks,EricSent from my iPhoneOn Aug 2, 2024, at 12:00, Scott Hanson ***@***.***> wrote:﻿
Did you attempt to change the "Windows 11 on ARM" properties and disable hybrid emulator option

**Comment by derwin12** [comment] 2024-08-02 19:14
Curious is this is those new laptops that just came out? I cant think of the name..

**Comment by ericleco** [comment] 2024-08-02 19:43
Yes it is. ARM (Snapdragon elite) based but it has an x86 emulator. I had asked if anyone used xlights on this zoom call before buying it but didn’t get an answer. The one I purchased is the ASUS Vivobook S15. It’s a sweet machine for the price (and I got it at $100 off) now if only xlights can work on it 😂. Thanks,EricSent from my iPhoneOn Aug 2, 2024, at 15:15, Daryl ***@***.***> wrote:﻿
Curious is this is those new laptops that just came out? I cant think of the name..

**Comment by keithsw1111** [comment] 2024-08-02 21:52
For now its not supported ... at some point it will be but not yet. Closing the ticket as having a ticket open for this has no impact on if/when it gets resolved.

**Closed by keithsw1111** 2024-08-02 21:52 UTC

**Comment by ericleco** [comment] 2024-08-02 22:40
Thanks for letting me know.  It might be a good idea to include the non-support on the download page (or somewhere) so that others aren't stuck in the same boat as I now.

Luckily, my old laptop is still semi functional so I will keep using it for now.

Thanks,
Eric

________________________________

**Comment by DanielFrei64** [comment] 2024-10-10 04:48
Same thing here. Bought the new surface pro 11 today. Xlights was my first install and it was a no-go. Gonna return the laptop tomorrow. Might be worth adding this to the downloads page that this doesn't work on ARM processors

**Comment by derwin12** [comment] 2024-10-15 14:18
Just an update to this closed ticket - Scott has made the changes and another user has confirmed it works on an ARM laptop.

**Comment by ericleco** [comment] 2024-10-16 21:58
Unfortunately, it doesn't seem to work with the latest version (2024.17).

[cid:91b6156e-7c1d-4b96-a29a-0f9d34cb054f]

Eric
________________________________

**Comment by computergeek1507** [comment] 2024-10-16 22:10
You need to use this special version for now, https://github.com/xLightsSequencer/xLights/releases/download/2024.17/xLights64_2024_17.exe

**Comment by DanielFrei64** [comment] 2024-10-16 22:14
As well, if it installs but crashes when you run it, install the OpenGL/CL compatibility pack from the windows store. I wasn't that far out of date, but since updating this it's worked fine since without crashing
https://apps.microsoft.com/detail/9nqpsl29bfff?hl=en-US&gl=US

**Comment by ericleco** [comment] 2024-10-16 22:23
Thanks!

I can confirm that it is working on ARM currently.  Greatly appreciated. Now the old laptop can get buried in the ground since it's on it's last electron (reason why I got a new one).

Eric
________________________________
