### ISSUE TITLE
Buffer Render Style changes

### ISSUE THREAD

**Issue by bcarriveau** [xLightsSequencer/xLights#3181] opened 2022-04-03 19:35 UTC
Edited as it doesn't seem to matter what effect is used. Sketch and Pinwheel tested here.

Appears that a buffer style change on a group seems to crash xLights with no report. If i start a new animation, 20fps, drop an  effect down on a group, then hover over the buffer styles and roll my mouse slowly, it seems hit a point / exit xLights.

Windows 10 21H2

xLights master as of this afternoon

**Comment by keithsw1111** [comment] 2022-04-05 07:34
Yeah there is more to it than that ... I just tried it and no crash ... can you share a layout and a sequence with one effect which we should change the buffer style on. I am assuming the buffer change is on the sequencer and not on the group itself but this isnt super clear in your problem description.

**Comment by bcarriveau** [comment] 2022-04-05 13:02
you bet, 

[xLightsProblem.zip](https://github.com/smeighan/xLights/files/8418298/xLightsProblem.zip)

![problem](https://user-images.githubusercontent.com/60801063/161759418-9536436b-4468-42a0-996f-8301399f3263.gif)

**Comment by AzGilrock** [comment] 2022-04-05 13:35
I'm not at home but take a look at what happens in the effect assist when it crashes.  Every time you change the render buffer the effect assist has to update for the new buffer size.  Maybe the EA doesn't like certain buffer types.  To rule this out you could try to test this with the effect assist window closed and see if the crash doesn't happen.

**Comment by derwin12** [comment] 2022-04-05 15:54
Crashes with or without the effect assist. It does not crash with the -8f (4+ days ago) nightly build .. it crashes since the sketching effect was added (using the last nights build for example).

**Comment by AzGilrock** [comment] 2022-04-05 16:53
Ok I'm really confused watching the video again.  What effect are you grabbing because the settings panel says its a Single Strand effect and it has the Single Strand icon but you are nowhere near that effect icon when you grab.  So is that the new Sketch Effect your grabbing?  Not sure why the effect panel is not updating.

Another thing that looks like a bug is lower on the grid there is a model highlighted dark blue.  The row with the currently active effect is supposed to be highlighted so when you drop the effect that row where you dropped should have highlighted.  I can try to test some of this tonight.

**Comment by derwin12** [comment] 2022-04-05 17:29
I did it with sketch .. couldnt do it with Single strand or ON.

**Comment by AzGilrock** [comment] 2022-04-05 17:41
So the solution is we disable the mouse wheel for that dropdown? :)

Just kidding but I've actually never used the wheel like that I always open the dropdown and then select the one I want.  When you scroll you can see from the effect assist how its rapidly trying to create and destroy render buffers.  That also means there are a ton of render actions having to be spawned and killed rapidly.

**Comment by bcarriveau** [comment] 2022-04-05 18:20
I'd cry without the mouse wheel option lol. It's probably easy when you know exactly what each render method does before selecting it but, us terrible sequencers need to easy roller methodology 🤣🤣. 

I'll complain if it's fixed or not anyways 🙈 
😊

**Comment by AzGilrock** [comment] 2022-04-06 04:18
Ok I tested and did cause a crash.  I could not cause the crash on Mac because it doesn't seem to update the combo-box when I scroll the mouse wheel.  So I moved over to Windows and go it to crash.  I just dropped a SingleStrand effect like I saw in the video.  What confused me on the video was your mouse was being shown way to the right of where it was actually clicking.   I don't have time to debug but I did grab the end of the log.  I'm thinking its something to do with when it got down to a buffer that caused it to spawn on the Background thread.

2022-04-05 21:12:59,301 17880 log_base [DEBUG] EffectsGrid::mouseDown effect selected SingleStrand.
2022-04-05 21:13:00,146 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:00,146 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:00,229 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:03,219 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:03,219 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:03,290 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:03,335 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:03,335 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:03,417 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:03,490 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:03,490 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:03,566 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:03,624 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:03,624 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:03,701 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:03,758 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:03,758 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:03,831 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:04,405 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:04,405 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:04,476 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:04,560 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:04,560 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:04,635 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:04,698 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:04,698 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:04,770 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:04,838 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:04,838 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:04,914 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:04,978 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:04,978 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:05,051 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:05,119 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:05,119 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:05,193 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:05,726 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:05,726 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:05,797 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:05,880 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:05,880 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:06,124 17880 log_base [DEBUG] Job pool new size 4.
2022-04-05 21:13:06,171 19512 log_jobpool [INFO] Background thread pool started with 11 threads
2022-04-05 21:13:06,175 17880 log_base [DEBUG] Render tree built for model Everything 3750ms-14100ms. 50 entries.
2022-04-05 21:13:06,175 17880 log_base [DEBUG] Rendering 1 models 208 frames.
2022-04-05 21:13:06,432 17880 log_base [DEBUG] Job pool new size 4.

**Comment by keithsw1111** [comment] 2022-04-06 06:14
I tried it in the debugger (post Kevin's changes today) and I cannot reproduce the problem. I scrolled through all the buffer options on both the single strand effect and the new sketch effect on the all flakes group and it does not crash. Maybe try again with tomorrows build with Kevin's fixes ... maybe he fixed it today.

**Comment by computergeek1507** [comment] 2022-04-06 11:42
I put a group in a group and the Per Model Horizontal Per Strand I added crashes. I have to add some logic for groups in groups still

**Comment by derwin12** [comment] 2022-04-06 12:46
I do have a group in a group (intentional) .. so I will try your code fix.

**Comment by derwin12** [comment] 2022-04-06 12:47
btw -- Keith you might still have my layout zip from the other day's zoom (when you were testing the controller test feature).. if that helps.

**Comment by computergeek1507** [comment] 2022-04-06 12:48
> I do have a group in a group (intentional) .. so I will try your code fix.

I haven't fixed it yet, I have been too busy lately with FMM

**Comment by AzGilrock** [comment] 2022-04-06 13:24
BTW I crashed with my own show directory I didn't use the one from here.  I just used my "Everything" group.  I never touched the Sketch effect so I don't think its involved.

**Comment by derwin12** [comment] 2022-04-07 14:06
Couldnt duplicate with last nights build.

**Comment by bcarriveau** [comment] 2022-04-08 01:42
Still closes for me on master.

**Comment by keithsw1111** [comment] 2022-04-08 02:42
Can you run it under the debugger and catch the crash?

On 8 Apr 2022, at 11:43 am, Bill Carriveau ***@***.***> wrote:

﻿

Still closes for me on master.

**Comment by bcarriveau** [comment] 2022-04-08 17:20
When I get back tonight I'll work on it!

**Comment by bcarriveau** [comment] 2022-04-08 23:38
I will post the entire call stack below the screen shot.
![2022-04-08 18_36_47-xLights (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/60801063/162546757-7b22f50a-5a62-4c9d-b62f-e989ca8122f8.png)

 	000000000089f5ae()	Unknown
 	000000000a28b020()	Unknown
 	000000000014bca0()	Unknown
 	000000001c820d00()	Unknown
 	00000000000000b0()	Unknown
 	nvoglv64.dll!00007fff7288afc3()	Unknown
 	nvoglv64.dll!00007fff7288a8b4()	Unknown
 	nvoglv64.dll!00007fff7288ab7f()	Unknown
 	nvoglv64.dll!00007fff728a2b64()	Unknown
 	nvoglv64.dll!00007fff728a2ce5()	Unknown
 	nvoglv64.dll!00007fff7294dda5()	Unknown
 	nvoglv64.dll!00007fff7294e0fc()	Unknown
 	nvoglv64.dll!00007fff7243ea89()	Unknown
 	nvoglv64.dll!00007fff725732fc()	Unknown
 	nvoglv64.dll!00007fff72572a6c()	Unknown
 	nvoglv64.dll!00007fff7257eb13()	Unknown
 	opengl32.dll!00007fff245e9c3a()	Unknown
 	SS2OSD.dll!00007fffd7aed704()	Unknown
 	SS2OSD.dll!00007fffd7af6edc()	Unknown
 	SS2OSD.dll!00007fffd7af7597()	Unknown
 	SS2OSD.dll!00007fffd7af6c5b()	Unknown
 	SS2OSD.dll!00007fffd7aed378()	Unknown
 	SS2OSD.dll!00007fffd7ae67ac()	Unknown
 	SS2OSD.dll!00007fffd7ae6637()	Unknown
 	gdi32full.dll!00007ffffb8b273e()	Unknown
>	Xlights.exe!wxGLCanvas::SwapBuffers() Line 803	C++
 	Xlights.exe!xlGLCanvas::FinishDrawing(xlGraphicsContext * ctx, bool display) Line 1188	C++
 	Xlights.exe!xlGridCanvasEmpty::render(wxPaintEvent & event) Line 51	C++
 	Xlights.exe!wxAppConsoleBase::HandleEvent(wxEvtHandler * handler, void(wxEvtHandler::*)(wxEvent &) func, wxEvent & event) Line 655	C++
 	Xlights.exe!wxAppConsoleBase::CallEventHandler(wxEvtHandler * handler, wxEventFunctor & functor, wxEvent & event) Line 666	C++
 	Xlights.exe!wxEvtHandler::ProcessEventIfMatchesId(const wxEventTableEntryBase & entry, wxEvtHandler * handler, wxEvent & event) Line 1432	C++
 	Xlights.exe!wxEventHashTable::HandleEvent(wxEvent & event, wxEvtHandler * self) Line 1039	C++
 	Xlights.exe!wxEvtHandler::TryHereOnly(wxEvent & event) Line 1628	C++
 	Xlights.exe!wxEvtHandler::TryBeforeAndHere(wxEvent & event) Line 4007	C++
 	Xlights.exe!wxEvtHandler::ProcessEventLocally(wxEvent & event) Line 1561	C++
 	Xlights.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Line 1534	C++
 	Xlights.exe!wxEvtHandler::SafelyProcessEvent(wxEvent & event) Line 1650	C++
 	Xlights.exe!wxWindowBase::HandleWindowEvent(wxEvent & event) Line 1547	C++
 	Xlights.exe!wxWindow::HandlePaint() Line 5319	C++
 	Xlights.exe!wxWindow::MSWHandleMessage(__int64 * result, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3095	C++
 	Xlights.exe!wxWindow::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 3883	C++
 	Xlights.exe!wxWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Line 2925	C++
 	[External Code]	
 	Xlights.exe!wxWindow::MSWSafeIsDialogMessage(tagMSG * msg) Line 2790	C++
 	Xlights.exe!wxWindow::MSWProcessMessage(tagMSG * pMsg) Line 2672	C++
 	Xlights.exe!wxGUIEventLoop::PreProcessMessage(tagMSG * msg) Line 142	C++
 	Xlights.exe!wxGUIEventLoop::ProcessMessage(tagMSG * msg) Line 160	C++
 	Xlights.exe!wxGUIEventLoop::Dispatch() Line 226	C++
 	Xlights.exe!wxEventLoopManual::ProcessEvents() Line 234	C++
 	Xlights.exe!wxEventLoopManual::DoRun() Line 288	C++
 	Xlights.exe!wxEventLoopBase::Run() Line 87	C++
 	Xlights.exe!wxAppConsoleBase::MainLoop() Line 377	C++
 	Xlights.exe!wxAppConsoleBase::OnRun() Line 299	C++
 	Xlights.exe!wxAppBase::OnRun() Line 342	C++
 	Xlights.exe!wxEntryReal(int & argc, wchar_t * * argv) Line 504	C++
 	Xlights.exe!wxEntry(int & argc, wchar_t * * argv) Line 175	C++
 	Xlights.exe!wxEntry(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * __formal, int nCmdShow) Line 297	C++
 	Xlights.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Line 362	C++
 	[External Code]

**Comment by bcarriveau** [comment] 2022-04-08 23:43
here are the logs for that also.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/8455811/xLightsProblem.zip)

**Comment by cybercop23** [comment] 2024-02-02 19:58
Gents... is this still an issue? If so, what are next steps?

**Comment by derwin12** [comment] 2024-02-02 20:17
Alex - cant duplicate anymore.

**Comment by AzGilrock** [comment] 2024-02-02 20:21
I just tried the steps I used to crash it and it's not happening so I'll close it.

**Closed by AzGilrock** 2024-02-02 20:21 UTC
Labels: Bug - Major, Waiting for user feedback, Effects, Sequencer
