### ISSUE TITLE
xlights Crash on Import

### ISSUE THREAD

**Issue by kbostick88** [xLightsSequencer/xLights#4378] opened 2024-03-01 16:28 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

xlights crashes when importing a sequence. Reproduced on multiple different layouts, with multiple different imports

https://github.com/xLightsSequencer/xLights/assets/17733692/33ef2da1-f528-4075-8873-7371cd3e1470

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Open a sequence
2. Click on import
3. navigate to a zipped sequence
4. click on the zip
5. xlights crashes

**Expected behavior**
A clear and concise description of what you expected to happen and why.
xlights should open the zipped sequence and show the import dialog box
**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10]
 - xLights version [e.g. 2024.04]

**Additional context**

**Attachments**
- https://drive.google.com/file/d/1mbMUM3nzPvIeGtc_Yj8lNeI1JKYAVVt9/view?usp=sharing

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by derwin12** [comment] 2024-03-01 18:44
Duplicate of #4377 
Something with compare and FPPConnect? Not clear why fpp connect would be called.

```
[01]	ADDR:0x00007ff64b70aa55	HMODULE:0x00007ff64ab80000	0000000000b8aa10	UtilFunctions.obj	?NumberAwareStringCompare@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z@938E75 
[02]	ADDR:0x00007fffa42991c2	HMODULE:0x00007fffa40d0000	00000000001c8bb0	FPPConnectDialog.obj	??0FPPConnectDialog@@QEAA@PEAVwxWindow@@PEAVOutputManager@@HAEBVwxPoint@@AEBVwxSize@@@Z@67E02 
```

**Comment by cybercop23** [comment] 2024-03-01 18:47
I'm able to use a ZIP and regular xsq file on a Mac w/o any issues. This seems to be Windows related.

**Comment by computergeek1507** [comment] 2024-03-01 19:50
It's the new sort code causing it.

**Comment by cybercop23** [comment] 2024-03-01 19:55
Yup... on allowccr.. we're looking it now.... may have a quick solution.. just dono why it works on mac and not on windows..

**Comment by cybercop23** [comment] 2024-03-01 21:58
Scott make a 3 letter change and seems to test okay now on both the mac and windows. Please try the nightly tonight.

**Comment by computergeek1507** [comment] 2024-03-01 22:36
Three important letters

**Comment by derwin12** [comment] 2024-03-01 22:48
Is it possible to push the new version out as .04 ?

**Comment by ssharpe83713** [comment] 2024-03-06 23:18
Import crashes on mine as well...Windows 11.  zip file attached.
[xLights_dbgrpt-14548-20240306T145121.zip](https://github.com/xLightsSequencer/xLights/files/14516701/xLights_dbgrpt-14548-20240306T145121.zip)

**Comment by cybercop23** [comment] 2024-03-07 00:13
It's fixed in the nightly. Try that.

**Closed** 2024-03-11 22:24 UTC
Labels: Duplicate, Waiting for user feedback, OS - Windows, Bug - Crash, Sequencer
