### ISSUE TITLE
Effects on top of each other

### ISSUE THREAD

**Issue by Poporacer** [xLightsSequencer/xLights#2417] opened 2020-12-16 04:57 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

My sequence has two effects, on the same line one over the top of the other one. I can independently move or delete one of the effects. I don't know what actually caused this. It is in several locations in my sequence.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)

I don't know how to reproduce, sorry, I did cut and paste some effects, but I can't say for certain if that caused the issue.

**Expected behavior**
A clear and concise description of what you expected to happen and why.

An effect should not be allowed to overlap

**Screenshots**

I attached a video that shows 2 of the same effects overlapping, the attached screenshot shows 2 different effects overlapping.
![image](https://user-images.githubusercontent.com/46263877/102305964-6cb06380-3f1e-11eb-8bf0-5be876b4132b.png)

**Versions (please complete the following information):**
 - OS: [Windows 10]
 - xLights version [2020.55 but I was using .54 previous with the same problem, upgrading didn't fix the problem.]

**Additional context**

**Attachments**

Video is here: https://drive.google.com/file/d/1W6HmFb5_Bka5k8QkbHuOHzbiHHQMYk_M/view?usp=sharing
Sequence is here: https://drive.google.com/file/d/1-UXdGWVhj_jXGq0uX4VDbWCni0oCHPyy/view?usp=sharing

- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment] 2020-12-16 13:20
Yep that used to happen in the old days.  There is a lot of protection to prevent overlaps.  But just showing us you caused it provides nothing to fix it.  Unless you can reproduce how to get into that situation I'd have to say you had a sequence with a preexisting problem that cannot happen in the latest version.  But once it gets into that situation should we pick one to delete for you?

**Comment by Poporacer** [comment] 2020-12-16 15:22
I understand that not being able to reproduce the problem creates extreme difficulty in determining the problem but sometimes looking at the end result can provide enough information to determine what protections in place were not enforced? This was a new sequence that was created on ver 2020.54. So the problem CAN happen in the latest version so there IS a flaw in your protections, and I understand that this might be a "one time" bug that never pops up again, but I thought you might want to be informed of any and all bugs? No, I don't need you to fix the sequence, I am trying to help make the program better but if you don't want bugs reported, then I will just keep using the program as is and work around things as they come along. 
Thanks for the great program! It is an amazing program and without all of your efforts, the lighting community could not create the shows we have today.

**Comment by AzGilrock** [comment] 2020-12-16 15:33
I didn't say a word about not wanting bugs reported but I don't give a fuck if you never report a bug again.

**Comment by Poporacer** [comment] 2020-12-16 18:20
@AzGilrock I don't know why you responded as you did? That was totally out of line! I reported a bug, and reported it as thoroughly as possible and I did not expect a resolution to MY problem as I had already fixed it prior to posting the bug. But your response insinuated that if someone can't reproduce a problem, then it isn't a bug and that people are wasting their time in reporting a bug. And why are you even looking at the Issues since you haven't contributed anything to xLights in almost a year? You HAVE provided great contributions in the past, but if you have no interest in improving xLights at this point, then maybe you should not respond to valid bug reports?

**Comment by nmiller0113** [comment] 2020-12-16 18:24
That's classy @AzGilrock. Delete my comment which was completely respectful, and your own that I was responding to which was not based on the language you used. I'm sure this one will be deleted as well, but those of us that follow the issues here were also emailed a copy of all the comments. That's the only reason I was ever aware of this report and commented in the first place. Great abuse of power deleting comments because you didn't like them....you're batting 1000 today.

**Comment by AzGilrock** [comment] 2020-12-17 13:08
I'll open this back up but please leave out commentary not relevant to the issue.  Nobody is here trying to hurt anyone's feelings.  I'm just being honest if someone doesn't post a way to cause this issue I don't believe anyone is going to be able to fix it because it could originate from so many different operations.  But who knows maybe a developer spent his entire night trying to find it.  If I think an issue is irrelevant I will close it immediately so like yesterday when you see me reply but not close it that means I accept it as an issue I'm not ignoring it and I'm not indicating anyone should never post issues again.  I don't have time for the drama this isn't Facebook.  I have seen this problem in past versions and fixed it so to me its logical to guess that it could have come from effects or presets pasted or imported from old sequences.  When you don't know how you did it all I can do is guess.  A lot of times I'm purposely replying in a way to prompt you to provide more info.

**Comment by Poporacer** [comment] 2020-12-17 17:41
Gil,

I really don’t care if you open this up or not, I was simply providing information in regards to a bug to help improve the program.  And I am fully aware that not being able to reproduce it makes it extremely difficult to troubleshoot if not impossible. However, by posting the bug, there might have been other issues posted that this post might have helped solve? And in my experience a bug report is just that a report, it is not a demand to do anything. If the report is helpful, then fine, if not, then round file it.

I have received a ton of bug reports myself on projects and many times they are pure garbage so I understand fully the process and that is why I try to be as detailed as I can. I have jumped on people that have bad-mouthed the xLights developers for not fixing a bug and find out that the bug report filed was complete garbage. 

We do not know each other, and you don’t understand where I am coming from, I do have a little computer knowledge under my belt, no where near what you have, and I will, and have taken hours of my time trying to duplicate bugs in xLights or testing features and will go out of my way to help in any way I can to make this a better program. Many times Keith has provided me directions in what might have caused the bug and I will test that theory and then provide the results. 

You stated that no one is trying to hurt anyone’s feelings. My skin is thick, you haven’t come close to hurting my feelings, but you have caused me to lose a little respect for you. I am totally fine with honesty.

Here is what I see: 

I file a somewhat complete bug report, not reproducible (yet).

You respond that it isn’t possible using the current version of xLights unless I was using an old sequence that had the problem previously. But then add the snide comment asking if I wanted you to fix my sequence. 
(but in your response below you stated that a lot of times you reply in a way to prompt us to provide more info? What direction did this response give me?)

I responded with additional information that I was using the current version and a new sequence, not re-hashing an old one so your theory was incorrect. Even the Check Sequence report states that the situation “shouldn’t be possible.” Maybe I mistook your tone in your response, but your response definitely had the tone of “don’t report it” 
(at least one other person felt the same way and BTW I do not know him or have ever had any interaction with him.)

Then you respond that you didn’t say a word about not reporting bugs and then your “I don’t give a fuck” response? WTH? Have I done something in the past to warrant this type of response?

I do think that the response that nmiller0113 provided was not relevant to the bug at hand and didn’t need to be posted, but I guess you hit a nerve with him? Have the two of you had bad blood in the past?

Keith provided information on some avenues to pursue in order to replicate the bug and when I finish the project that I am working on, I will try to reproduce it.

I don’t know if this will get posted to the GitHub account, if so, please delete it as it has no relevance to the topic at hand.

Let’s put this behind us and continue to work towards the greater good of creating an amazing program (which it already is!)

Rick Harris

**Comment by AzGilrock** [comment] 2020-12-17 18:22
I'll leave these replies here for maybe a day but no need for others to be reading this mess a month from now.  I still think everyone reads too much into what I say and is on edge looking to be offended.  My replies have been very short and then I get sermons in return.

**Comment by cybercop23** [comment] 2024-02-05 23:19
Should this be closed?

**Closed** 2024-02-05 23:48 UTC
Labels: Waiting for user feedback, Effects, Sequencer
