### ISSUE TITLE
Lagging issue on M2 chip

### ISSUE THREAD

**Issue by rparmer** [xLightsSequencer/xLights#3919] opened 2023-08-14 23:47 UTC
**Describe the bug**

I've got a new MacBook Pro 16" with the M2 Max chip and I am running into major lagging issues.  This is impacting not only sequence rendering and playback, but it's also impacting the layout screen.  I am using a 3D layout and there is a ~1 second delay from the time I move to the time xLights responds.  My wife was creating a new sequence and she was having the same issue when trying to create new timing marks as well as adding some simple effects.  I turned of both GPU rendering and hardware decoding and it got better, but there was still a noticeable delay.  We do have a pretty dense display so at first I just chalked it up to that.  However, for testing I moved the show to my 14" M1 Pro machine and it worked without issue.  No delay...and with GPU and hardware decoding enabled.  I'm guessing this must be something specific to the M2.

I'm not sure what info would be beneficial since this doesn't appear to be a sequence specific issue.  But if need any additional info please ask and I'll upload what I can.

Thanks

**Versions (please complete the following information):**
 - OS: Mac 13.5
 - xLights version 2023.12 (and 2023.11)

**Comment by rparmer** [comment] 2023-08-15 02:15
I don't see anything much, but here are the logs between the 2 machines.  On both I opened the same show, went to the layout page, and just moved the preview around.  On the M2 there was lag, M1 no issue.

[xLights_logs_no_lag.txt](https://github.com/smeighan/xLights/files/12340736/xLights_logs_no_lag.txt)
[xLights_logs_with_lag.txt](https://github.com/smeighan/xLights/files/12340737/xLights_logs_with_lag.txt)

**Comment by Darzoom** [comment] 2023-08-18 12:44
Seeing same issue on the Intel based Mac.  

Monterey 12.6.8
2.6 Quad-Core Intel COre i7
16GB LPDDR3

Renders and moving effects in a sequence literally stops xlights and I have to walk away from the computer.

**Comment by cdoades** [comment] 2023-08-19 13:44
I am having the same issue. We tried a couple changes in the "other" settings, which helped for a little while until the next update came out. Now it's worse than ever.  I took screen shots of my macs processes and RAM. Both are fine and not being taxed to death by Xlights. It's got to be an issue in XLights itself...

**Comment by cdoades** [comment] 2023-08-19 13:55
@Darzoom @rparmer @dkulp No sooner did I post my previous comment, I think I stumbled on the cause of the problem.  My screen's refresh rate was set to "ProRes."  I thought on a whim, why not play around with resolution settings since someone on facebook suggested it could be a resolution issue,  I set my refresh rate to 60Hz and it's night and day difference on Xlights performance.  So far, no lag issues what so ever.  I will do some more testing, but check your refresh rates and try setting it to 60Hz and see if that solves your issue.

**Comment by rparmer** [comment] 2023-08-19 15:31
@cdoades Thanks for the advice.  I did try changing the refresh to 60Hz but unfortunately that did not make a difference.  I also checked the settings on my other machine (M1 pro) that is not having any issues and it has the refresh rate set at "ProMotion" 🤷‍♂️.  I'll keep poking around to see if I can find anything.  But like you said system resources seem to be fine.

**Comment by cdoades** [comment] 2023-08-19 16:09
> @cdoades Thanks for the advice. I did try changing the refresh to 60Hz but unfortunately that did not make a difference. I also checked the settings on my other machine (M1 pro) that is not having any issues and it has the refresh rate set at "ProMotion" 🤷‍♂️. I'll keep poking around to see if I can find anything. But like you said system resources seem to be fine.

Did you try restarting the Mac after making the change? I did.

**Comment by rparmer** [comment] 2023-08-19 17:44
I did.  It seems to help temporarily but after about a min or so the issue still comes back

**Comment by whirlywhopter** [comment] 2023-08-22 14:53
Also seeing very similar kinds of issues on a 16" MacBook Pro, M1 Max, 64GB.  Refresh is set to 60Hz and I have tried various settings options with no significant changes.  I did not see it mentioned earlier but I also see random freezes in the house preview when playing a sequence.  The audio continues normally but the sequence display occasionally freezes briefly.

**Comment by sslupsky** [comment] 2023-09-05 03:07
I have encountered this issue today running xLights 2023.13 on 16" MacBook Pro, M2 Max, 96GB.  Severe stuttering and lag when navigating 3D layout which makes xLights unusable.

**Comment by AzGilrock** [comment] 2023-09-05 13:49
Nope it wouldn't have anything to do with my work.  The change for model placement only occurs when you click to place the model it calculates which angle the view is so it can adjust the axis that is being controlled for the handle you move to size the model.  Its a single calculation when the first model placement click is done.   And that same math is run all the time when you Pan the view because it figures out the view angle to know which axis to Pan along.

I think its more likely a resolution/refresh issue.  I use an M1 Max laptop and at home it works great.  I used the laptop for a presentation at the SoCal mini and I experienced lagging issues.  Only difference was to present I was hooked up to a projector which forced a different resolution on me.

**Comment by sslupsky** [comment] 2023-09-05 14:49
@AzGilrock  Thanks for the feedback.  I read the OP issue again and it refers to version 2023.11.

I googled around a bit and came across some Ventura issues with pinch to zoom.  One report indicated that after pinch to zoom was fixed, it introduced a new problem with two finger scrolling.  These reports are sporadic so there is uncertainty if those reports have anything to do with the issue reported here.  Not clear yet if this is an xLights issue or macOS.

**Comment by Ronniek6** [comment] 2023-09-20 01:50
I have recently changed to MacBook Pr M2 Ventura 13,5,2 from windows and I have the same problem. I noticed that if I Zoom in on the song it goes away. Hope this helps

**Comment by sslupsky** [comment] 2023-10-14 04:24
Problem still exists in 2023.16.

I wonder if this has something to do with this QT issue:
https://bugreports.qt.io/browse/QTBUG-65364

**Comment by sslupsky** [comment] 2023-10-14 22:20
@dkulp This issue is similar:
https://github.com/smeighan/xLights/issues/3827

It is closed but should probably should be reopened.

**Comment by AzGilrock** [comment] 2023-10-14 23:34
Doesn’t help to have multiple issues open for the same thing.

**Comment by cybercop23** [comment] 2024-01-28 23:47
Is this still an issue? Can someone replicate it? I'm on 14.3/M2/16GB no issues. Try 2024.2 and/or hop on the TestFlight wagon and test. 

If no issues or updates, @rparmer  please close.

**Comment by Ronniek6** [comment] 2024-01-29 00:25
Thanks, I have no issues now.

Ronnie Kelley

**Comment by cybercop23** [comment] 2024-01-29 05:24
> There is still a small amount of lag on my M2 Max but the frequency of the lag events has reduced significantly. I would say xLights is usable again in Layout model on my M2 Max MBP when using the built in screen. I have not had an opportunity to test the sequencer yet.

Please try the latest version 2024.2 and/or even install TestFlight to get nightly builds. If you still have and issue, I'd sugged you open as new issue, refrence this one as to keep them separate and not keep on piling on. 
I'm runngn on a MBP M2 awith 14.3 w/o issues.

**Comment by rparmer** [comment] 2024-02-02 01:55
I am still seeing some lag on the layout page as well.  It seems to be much better then it was before, but there is still some lag.  Testing on my other M1 Pro and it still works without issues.  Something with the M2 Max is just off.

**Comment by cybercop23** [comment] 2024-02-05 15:51
@dkulp any info you need on this M2 Max issue? Should this remain open?

**Comment by cybercop23** [comment] 2024-02-09 01:14
@rparmer I'm only on an M2 but one of the other regular zoomers is on a M2 Max and no issues. IDK what we can do here since it may be uniquely related to you. We know others tha tuse M2 Maxs too.... I'm going to close this, but please fell free to reopen if you continue to have issues and have logs that you can upload.

**Comment by sslupsky** [comment] 2024-02-09 13:50
> IDK what we can do here since it may be uniquely related to you. We know others tha tuse M2 Maxs too.

I indicated that there are still lag issues and I am using an M2 Max so the problem is not unique to @rparmer .  There has be no comment from a developer suggesting anything was done to address this issue.  You closing this issue does not help the situation.  Please re-open this issue.

**Comment by cybercop23** [comment] 2024-02-09 13:55
Happy to reopen, but there's been no further info on either issues. So, pleae make sure you are running on the latest OS 14.3 and latest xLights 2024.2. Start a screen recording and perform the same tests and post that plus Tools -> Package Logs from that same session.
Also..  feel free to hop on zoom so we can take a look.. although sometimes being on zoom doesn't help matters.

**Comment by sslupsky** [comment] 2024-02-09 14:00
I am happy to help out if there is someone that will take the time to look into this.  If you have a moment, I can hop onto Zoom now and show you?

**Comment by cybercop23** [comment] 2024-02-09 14:01
Hopon

**Comment by cybercop23** [comment] 2024-02-09 14:31
Okay.. so seems to have been "mostly" resolved with the latest version 2024.2. @sslupsky will upgrade OS to 14.3.1 When it happened before it was "always" on the build in display using the trackpad. Does no happen if running xLights on external monitor. We turned off GPU rendering...

@rparmer is this same senario for you? A) is it still an issue for you B) if so, can you also upgrade both OS and xLights and share the results?

**Comment by sslupsky** [comment] 2024-02-09 15:33
Here is a screen recording of what we were discussing earlier on zoom.  I recorded this after I upgraded to 14.3.1.


https://github.com/xLightsSequencer/xLights/assets/16888734/a7c56217-e26c-4716-a4ea-7141f5d37d08

**Comment by sslupsky** [comment] 2024-02-09 15:45
Here is another screen recording.  If I continuously pan there is no discernible lag.  I can reliably reproduce the lag by pausing and then moving again.

https://github.com/xLightsSequencer/xLights/assets/16888734/08bdb90d-3ac0-4545-9d51-281bd01ce68e

**Comment by cybercop23** [comment] 2024-02-09 16:51
Thanks for doing the upgrade. Can you please do it again, since a lot of time has passed... maybe like 2 or 3 tries and then Tools -> Package Logs and upload the zip file?

**Comment by cybercop23** [comment] 2024-02-09 17:21
Argg.... looks like nothing logged during the minute you were "sliding around" after you started xlights and ran package logs..

2024-02-09 09:53:28,474 8072043584 log_base [DEBUG] In Post Startup
2024-02-09 09:53:28,474 8072043584 log_base [DEBUG] User email address: <email>xxxxxxxxxx</email>
<slide slide>
2024-02-09 09:54:25,380 8072043584 log_base [DEBUG] RecalcStartChannels takes 370ms.
2024-02-09 09:54:25,751 8072043584 log_base [DEBUG] RecalcStartChannels takes 369ms.
2024-02-09 09:54:25,769 8072043584 log_base [DEBUG] CheckSequence: Checking sequence.    <<==== package logs

**Comment by sslupsky** [comment] 2024-04-14 22:27
Lag is back with a vengeance on my M2 MBP with the last few 2024 releases (currently 2024.08).

**Comment by timcara** [comment] 2024-04-19 01:24
@sslupsky I'm dealing with the issue as well, but I have M3 Sonoma. Choppy almost a majority of time and gets worse after a few minutes. Issue has occurred on both 2024.08 and 2024.09.

**Comment by tucsonlights** [comment] 2024-05-31 19:39
> Lag is back with a vengeance on my M2 MBP with the last few 2024 releases (currently 2024.08).
I have been getting the lag issue in my layout since picking up my M3 pro. Zoom is glitchy and pan is hit or miss but mostly glitchy. I have tried with gpu rendering and without. turned off promotion. Not sure if it had something to do with the peripherals like mouse or trackpad.

**Comment by allendotson** [comment] 2024-06-24 22:55
I'm on a new mac mini m2 pro, and have the lag issue.  The lag does go away if I uncheck "GPU Rendering".

**Comment by allendotson** [comment] 2024-06-24 23:03
Hey, the house preview window looks unaffected by this.  So perhaps it is related to some raycast algorithm to detect what model the mouse is hovering over?

**Comment by allendotson** [comment] 2024-08-06 02:40
> I’d try a mouse just to rule out the touchpad interface. I seem to remember touchpad uses different code

I have disabled my magic mouse and rebooted my machine with a wired mouse attached. There was no change in behavior, which would rule out differences in touchpad vs non. 

What information would you need captured in order to track down the bug?

**Comment by gavinw6662** [comment] 2024-08-29 01:30
I recently purchased an M2 Max Mac Studio and I’ve had nothing but problems with stutter/lag. It seems to come and go but more often than not I can trigger it while zoomed in on the timeline. It plays back at 2-3 fps with noticeable stutter/lag. However, I don’t see any issues when I’m zoomed out. It plays back at 40 fps no problem. 

I opened the same sequence on my wife’s M2 MacBook Air and it plays back without any issue. No stutter or lag. 

Maybe the issue is if/when using an M2 Max chip?

BTW I’m a noob and only just started with this hobby so I have just a couple of elements for the first year. Nothing complicated (to render) at all.

**Comment by cdoades** [comment] 2024-08-29 12:47
> I recently purchased an M2 Max Mac Studio and I’ve had nothing but problems with stutter/lag. It seems to come and go but more often than not I can trigger it while zoomed in on the timeline. It plays back at 2-3 fps with noticeable stutter/lag. However, I don’t see any issues when I’m zoomed out. It plays back at 40 fps no problem.
> 
> I opened the same sequence on my wife’s M2 MacBook Air and it plays back without any issue. No stutter or lag.
> 
> Maybe the issue is if/when using an M2 Max chip?
> 
> BTW I’m a noob and only just started with this hobby so I have just a couple of models for the first year. Nothing complicated (to render) at all.

So what I was suggested to do was check your display settings.  If your computer is set to use “Pro Res”, try changing that to a different refresh rate. I think mine is set to like 60Hz or something. I’m not at my laptop at the moment to check.  Then reboot your computer.  It drastically improved the performance.

**Comment by gavinw6662** [comment] 2024-08-29 18:11
> > I recently purchased an M2 Max Mac Studio and I’ve had nothing but problems with stutter/lag. It seems to come and go but more often than not I can trigger it while zoomed in on the timeline. It plays back at 2-3 fps with noticeable stutter/lag. However, I don’t see any issues when I’m zoomed out. It plays back at 40 fps no problem.
> > I opened the same sequence on my wife’s M2 MacBook Air and it plays back without any issue. No stutter or lag.
> > Maybe the issue is if/when using an M2 Max chip?
> > BTW I’m a noob and only just started with this hobby so I have just a couple of models for the first year. Nothing complicated (to render) at all.
> 
> So what I was suggested to do was check your display settings. If your computer is set to use “Pro Res”, try changing that to a different refresh rate. I think mine is set to like 60Hz or something. I’m not at my laptop at the moment to check. Then reboot your computer. It drastically improved the performance.

Thanks for the suggestion. I already tried that without any luck. Since it’s a Mac Studio I use external monitors which are 1080p monitors. They are capable of 75 hz refresh so I changed the display to 60 but still have the same issue. When I zoom in on the timeline and then play a section of the sequence the time scrubber bar stutters, and the playback is choppy in house preview. Also, it tends to play at 2-3 FPS. When it acts up like this it gets very hard to sync effects with music.

**Comment by allendotson** [comment] 2024-08-29 18:24
I noticed an interesting thing when the lagging is happening in the sequencer. If you shake the mouse while over the preview, it fixes it quickly. It must be related to the issue with layout view, but I can't find a recipe to cause it.

**Comment by derwin12** [comment] 2024-08-29 18:57
Are these related?
https://github.com/wxWidgets/wxWidgets/issues/18516
https://github.com/wxWidgets/wxWidgets/issues/24224

**Comment by gavinw6662** [comment] 2024-08-30 23:25
I jumped onto the xlights zoom today to discuss what I’ve been experiencing. What we found was that i could duplicate my problem when not sharing my screen but it acted just fine when i shared my screen. The running hypothesis is that my issue may have something to do with how the screen is rendering out to the screen.  Which, is not a problem when sharing on zoom. Almost like it bypasses whatever causes my issue. 

While getting setup to join zoom i accidentally unplugged one of my monitors (run dual 1080p monitors) which appeared to fix the problem. I then plugged the 2nd monitor in and restarted my Mac Studio. When running dual monitors I was able to replicate my issue again. I then unplugged my second monitor again and so far no issues. 

I probably wont be able to work on my sequnce this weekend. But when i get back to it i will try with only 1 monitor plugged in to see if that solves my problem?  If so then the question is ‘why’ does it resolve the stutter.

**Comment by derwin12** [comment] 2024-08-30 23:56
I have read similar accounts for other software using wxwidgets.
Also try disabling this .. it reduces the hit on the sequencer tab for refreshes.
![image](https://github.com/user-attachments/assets/03b46427-e652-4f26-915b-c409a26e3854)

**Comment by gavinw6662** [comment] 2024-09-03 01:30
Working on a single monitor solves all my problems. No stutter or lag issues at all today. Matter of fact, this also solved another issue I was having. Working in the 3D view was a total nightmare. So much stutter. But, that’s also fixed by working on a single monitor. 

I read a little on wxwidgets and it’s likely the culprit here. But I can’t tell you how.

**Comment by sslupsky** [comment] 2024-09-03 03:13
It is not so annoying these days but I can get it to lag repeatably using my trackpad on my MBP if I touch with two fingers and hold without lifting my fingers then move left or right, then hold, then move back, hold, then move, hold, ... etc.  Each time after holding for several seconds I will experience a 1 or 2 second lag before the layout updates.  If I am continuously moving around without the "hold" then I do not experience the lag much if at all.

**Comment by DonMc33** [comment] 2024-09-05 02:07
Eqiupment:
-Mac M2 Max, 64GB memory, Sonoma 14.6.1, 12 core(8 perf, 4 efficiency), 38 GPU, 500GB SSD storage.
-xLights 2024.15

ISSUE:
-FPS runs at the expected 40fps when House Preview is on main monitor, but when on extended monitor FPS slowly builds after the sequence is started, but never gets over 30 FPS.

Information:
I tried to grab this using the Mac screen recorder, but as soon as the recorder is started, with the sequence playing, the FPS then increases from 30 FPS to the expected 40 FPS.  When the screen recorder is closed, FPS drops back to approximately 30 FPS.

-Images attached-
Screenshot 1, sequence running with House Preview on the extended monitor, 

Recording - sequence running with House Preview on the extended monitor, once screen recording is started, the FPS increases from 30 FPS to 40 FPS, moved the House Preview window down from the extended monitor to the main monitor and back, held at 40 FPS, as long as screen recording continued.

Screenshot 2 shows where the FPS drops to 30 FPS after the screen recorder is closed.

![Screenshot 1_29 6 FPS](https://github.com/user-attachments/assets/8285ddd0-a0ea-4312-a301-b9455bca2ff0)
![Screenshot 2_40 FPS](https://github.com/user-attachments/assets/5cfafd09-0940-4dc9-82c6-96282530a732)

**Comment by DonMc33** [comment] 2024-09-05 02:08
Recording referenced above

https://github.com/user-attachments/assets/803948b2-1aeb-4cbe-87d6-af6d2ad3edbe

**Comment by allendotson** [comment] 2024-09-05 03:34
I'm also throwing in a report that unplugging my second monitor solves the issue. I didn't even need to restart xlights... just unplugging made the bug stop.  I'm running dual 1080p @ 60hz.

**Comment by dkulp** [comment] 2024-09-06 17:28
I've been trying to reproduce this all morning with my m2max MacBook Pro with one and two external displays without any luck.   I haven't seen any lag at all no matter where I place the preview windows, the main window, etc...

**Comment by DonMc33** [comment] 2024-09-06 20:55
Thank you for working this issue Dan.

In my case, I have a Mac Studio, M2 Max, 64GB memory, Sonoma 14.6.1, 12 core(8 perf, 4 efficiency), 38 GPU, 500GB SSD storage.  xLights 2024.15.

The issue is very repeatable on this system, as long as the House Preview is on the main monitor with the sequencer open, when running the sequence, it runs at 40 fps.  If I drag the House Preview to an extended monitor, frame rate drops to approximately 30, when I drag it back to the main monitor it resumes 40 FPS playback.

Will gladly provide any additional information that may be required while looking at the issue.

**Comment by sslupsky** [comment] 2024-09-06 21:33
@dkulp Did you have a chance to view the two video's I posted earlier?  Those videos show a repeatable way to experience the lag in the layout.

**Comment by derwin12** [comment] 2024-09-07 16:49
(I dont have a mac) .. Just some google answers here.. try 'em ?

1. https://community.adobe.com/t5/after-effects-discussions/psa-fix-for-display-or-preview-lag-on-macs-with-dual-screens/td-p/14068035
2.  https://discussions.apple.com/thread/251524344?sortBy=rank
3. "Hey, I just found a random but odd fix. Try switching off promotion and using 60hz on ur laptop display."
4. "Just want to update when I turn on the "Display have separate Spaces" as suggested above it does help to minimize the lag especially when dragging and zooming. Will try and use longer to see if the problem comes back." - https://forum.vectorworks.net/index.php?/topic/113501-vw2024-terrible-lag-on-second-monitor/page/3/
5. "Solution: turn ON Displays Have Separate Spaces under System Settings > Display and Dock > Mission Control." - https://community.adobe.com/t5/after-effects-discussions/psa-fix-for-display-or-preview-lag-on-macs-with-dual-screens/td-p/14068035

**Comment by DonMc33** [comment] 2024-09-07 18:58
Thank you Daryl.  I did try each of the 5 suggested resolutions that you were able to find via Google.  I tried each of the 5, however, the did not improve the FPS when the house preview was moved to the extended monitor.  

Appreciate the suggestions!

**Comment by gavinw6662** [comment] 2024-09-11 01:07
@dkulp 
> I've been trying to reproduce this all morning with my m2max MacBook Pro with one and two external displays without any luck. I haven't seen any lag at all no matter where I place the preview windows, the main window, etc...

When you were testing, were you still using the native laptop screen as a 3rd monitor?  I wonder if for some reason it's more reliable on a MacBook because of how it may be determining the primary display as being the laptop screen?  I know I'm grasping at straws, but it was a night and day difference for me when I removed the 2nd monitor from my setup.

**Comment by dkulp** [comment] 2024-09-11 01:25
I tried clam shelling it closed as well, changed the primary to different monitors, etc...  Could not reproduce.

**Comment by dkulp** [comment] 2024-09-25 00:37
Could folks give 16.1 a try and see if the behavior changes at all.  I still haven't been able to reproduce anything on my three monitor setup, but hopefully some of the changes/optimizations done for 16.1 will help.

**Comment by gavinw6662** [comment] 2024-09-25 01:10
@dkulp 

I was gonna post an update here before I saw your update.

I upgraded to the most recent MacOS and the most recent xlights release and everything is working wonderfully for me. 

I can now run dual monitors, with my house preview on my second monitor and my sequence timeline on the other and…..I'm not seeing the lag/stutter that I saw before. So far the new updates appear to be working.

**Comment by rparmer** [comment] 2024-09-25 03:00
I am not seeing anymore lagging issues either.  I'll keep playing with it for the next few days but so far so good.

**Comment by sslupsky** [comment] 2024-09-25 04:19
Lag in layout is still there in 16.1 about the same as it was.  Continuous movement doesn't show the problem.  Stop and start movements tend to reveal the lag.  I can reliably reproduce it (see my video above).  Happy to jump on zoom with you if you want to discuss.

**Comment by DonMc33** [comment] 2024-09-25 11:54
Updated to xLights 16.1, still had lagging issues with two monitors.

Read @gavinw662 post that he also upgraded the Mac OS to the latest, so upgraded to Sequia 15 and NO MORE LAGGING, issue resolved for me!!

**Comment by sslupsky** [comment] 2024-09-25 17:06
Yeah, I can confirm that updating to Sequoia eliminated the lag in the layout for me.

**Comment by derwin12** [comment] 2024-09-25 17:55
I think that makes it 3 thumbs up! .. Thanks Dan and Mac OS update ...

**Closed by derwin12** 2024-09-25 17:55 UTC
Labels: OS - MacOS, Layout
